package:
  name:    flexbox
  version: 0.0.1

source:
  path: .
#  git_rev: experimental
#  git_url: https://github.com/cicwi/flexbox.git
# 
requirements:
  build:
    - python
    - setuptools
    - scikit-image >=0.13.0
    - scipy >=0.14
    - imageio
    - matplotlib
    - transforms3d
    - toml
    - astra-toolbox >1.8.3
    - xraylib >=3.3.0
    - tifffile

  run:
    - python >3.0
    - numpy >1.0
    - scikit-image >=0.13.0
    - scipy >=0.14
    - imageio
    - matplotlib
    - transforms3d
    - toml
    - astra-toolbox >1.8.3
    - xraylib >=3.3.0
    - tifffile

test:
  imports:
    - flexbox

about:
  home: https://github.com/cicwi/flexbox
  license:
  license_file:


# Use:
# > conda build -c astra-toolbox/label/dev -c conda-forge -c owlas .
# > anaconda login
# > anaconda upload /ufs/kostenko/miniconda3/conda-bld/linux-64/flexbox-0.0.1-py36_0.tar.bz2

# Add package by: conda install -c astra-toolbox/label/dev scipy imageio matplotlib toml astra-toolbox scikit-image xraylib
